// Pre-configured common branch tasks for Indian banking operations
// Generated from PRECONFIGURED_TASKS_TEMPLATE.csv
const PRECONFIGURED_TASKS: Task[] = [
  {
    id: "task-daily-cash-reconciliation",
    name: "Daily Cash Reconciliation",
    frequency: "Daily" as const,
    dueDate: new Date().toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-daily-deposit-verification",
    name: "Verify Daily Deposits & Withdrawals",
    frequency: "Daily" as const,
    dueDate: new Date().toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-daily-cheque-clearance",
    name: "Monitor Cheque Clearance Status",
    frequency: "Daily" as const,
    dueDate: new Date().toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-weekly-npa-review",
    name: "Weekly NPA Account Review",
    frequency: "Weekly" as const,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-weekly-compliance-check",
    name: "Weekly Compliance Check - KYC & AML",
    frequency: "Weekly" as const,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-weekly-loan-documentation",
    name: "Review Loan Documentation & Agreements",
    frequency: "Weekly" as const,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-weekly-customer-follow-up",
    name: "Customer Follow-up for Pending Applications",
    frequency: "Weekly" as const,
    dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-interest-accrual",
    name: "Verify Monthly Interest Accrual & Posting",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-charges-report",
    name: "Generate Monthly Charges Return Report",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-npa-classification",
    name: "Monthly NPA Classification & Provisioning",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-recovery-letters",
    name: "Send Recovery Letters for Overdue Accounts",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-reconciliation",
    name: "Monthly Bank Reconciliation Statement",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-audit-trail",
    name: "Review Audit Trail & Transaction Logs",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-monthly-staff-training",
    name: "Conduct Monthly Staff Training/Updates",
    frequency: "Monthly" as const,
    dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-quarterly-npa-review",
    name: "Quarterly NPA Review & Board Report",
    frequency: "Quarterly" as const,
    dueDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-quarterly-compliance-audit",
    name: "Quarterly Compliance Audit Report",
    frequency: "Quarterly" as const,
    dueDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-quarterly-asset-quality",
    name: "Quarterly Asset Quality Review",
    frequency: "Quarterly" as const,
    dueDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-quarterly-recovery-performance",
    name: "Quarterly Recovery Performance Analysis",
    frequency: "Quarterly" as const,
    dueDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-annual-internal-audit",
    name: "Annual Internal Audit & Inspection",
    frequency: "Annual" as const,
    dueDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-annual-statutory-audit",
    name: "Annual Statutory Audit",
    frequency: "Annual" as const,
    dueDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-annual-compliance-certification",
    name: "Annual Compliance Certification",
    frequency: "Annual" as const,
    dueDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-annual-policy-review",
    name: "Annual Policy Review & Updates",
    frequency: "Annual" as const,
    dueDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-annual-risk-assessment",
    name: "Annual Risk Assessment & Mitigation",
    frequency: "Annual" as const,
    dueDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    completed: false,
    createdAt: new Date().toISOString(),
  }
];
